# syntax = docker/dockerfile:experimental
ARG atom
FROM gentoo/portage AS portage
FROM gendo-builder:${atom}-deps
ARG atom
ENV FEATURES="binpkg-multi-instance -cgroup -sandbox -usersandbox -ipc-sandbox -network-sandbox -pid-sandbox"
RUN \
 --mount=type=tmpfs,target=/var/tmp/portage \
 --mount=type=bind,from=portage,source=/var/db/repos/gentoo,target=/var/db/repos/gentoo,rw \
 emerge --buildpkgonly --verbose --oneshot ${atom/_/\/}
LABEL gendo=pkg
